AWSTemplateFormatVersion: 2010-09-09
Description: ---
#Metadata:

Parameters:

  AmiId:
    Type: AWS::EC2::Image::Id

  ApplicationName:
    Type: String

  AssociatePublicIpAddress:
    Default: false
    Type: String

  CertificateArn:
    Default: none
    Type: String

  CodeDeployApplication:
    Default: none
    Type: String

  CreateElasticFileSystem:
    Default: false
    Type: String

  CreateLoadBalancer:
    Default: false
    Type: String

  HealthCheckPath:
    Default: '/api/health-check'
    Type: String

  InstanceType:
    Type: String

  KeyName:
    Default: none
    Type: String

  LoadBalancerArn:
    Default: none
    Type: String

  LoadBalancerListenerArn:
    Default: none
    Type: String

  LoadBalancerScheme:
    AllowedValues:
      - internal
      - internet-facing
    Default: internet-facing
    Type: String

  LoadBalancerType:
    AllowedValues:
      - application
      - network
    Default: application
    Type: String

  Port:
    Default: 80
    Type: String

  Protocol:
    Default: HTTP
    Type: String

  SubnetIdList:
    Type: List<AWS::EC2::Subnet::Id>

  Sequence:
    Default: 1
    Type: String

#  SslPolicy:
#    Default: ELBSecurityPolicy-FS-1-2-Res-2019-08
#    Type: String

  Stage:
    Type: String

  SubnetA:
    Default: none
    Type: String

  SubnetB:
    Default: none
    Type: String

  UserData:
    Default: ''
    Type: String

  VpcCidr:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

#Mappings:

Conditions:

  CreateCodeDeployGroup: !Not [ !Equals [ !Ref CodeDeployApplication, none ] ]
  CreateElasticFileSystem: !Equals [ !Ref CreateElasticFileSystem, true ]
  CreateHttpListener: !Equals [ !Ref CertificateArn, none ]
  CreateHttpsListener: !Not [ !Equals [ !Ref CertificateArn, none ] ]
  CreateLoadBalancer: !Equals [ !Ref LoadBalancerArn, none ]
  CreateLoadBalancerListenerRule: !Not [ !Equals [ !Ref LoadBalancerListenerArn, none ] ]
  HasKeyName: !Not [ !Equals [ !Ref KeyName, none ] ]
  HasPublicIpAddress: !Equals [ !Ref AssociatePublicIpAddress, true ]

Resources:

#1) Launch Template
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !GetAtt IamInstanceProfile.Arn
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !If [ HasKeyName, !Ref KeyName, !Ref 'AWS::NoValue' ]
        NetworkInterfaces:
          - AssociatePublicIpAddress: !Ref AssociatePublicIpAddress
            DeviceIndex: 0
            Groups:
              - !Ref SshSecurityGroup
              - !Ref WebSecurityGroup
#        SecurityGroupIds:
#          - !Ref SshSecurityGroup
#          - !Ref WebSecurityGroup
        UserData:
          'Fn::Base64': !Sub |
            #!/bin/bash
            ${UserData}

#2) Auto Scaling Group
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MaxSize: '1'
      MinSize: '1'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}
          PropagateAtLaunch: true
        - Key: Stage
          Value: !Ref Stage
          PropagateAtLaunch: true
      TargetGroupARNs:
        - !Ref TargetGroup
      VPCZoneIdentifier: !Ref SubnetIdList

#3) Load Balancer:
  LoadBalancer:
    Condition: CreateLoadBalancer
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Sub ${ApplicationName}-${Stage}-lb-${Sequence}
      Scheme: !Ref LoadBalancerScheme
      Subnets: !Ref SubnetIdList
      Type: !Ref LoadBalancerType

  LoadBalancerHttpListener:
    Condition: CreateHttpListener
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !If [ CreateLoadBalancer, !Ref LoadBalancer, !Ref LoadBalancerArn ]
      Port: 80
      Protocol: HTTP
  #      SslPolicy: !Ref SslPolicy

  LoadBalancerHttpsListener:
    Condition: CreateHttpsListener
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !If [ CreateLoadBalancer, !Ref LoadBalancer, !Ref LoadBalancerArn ]
      Port: 443
      Protocol: HTTPS
  #      SslPolicy: !Ref SslPolicy

  LoadBalancerHttpsRedirectListener:
    Condition: CreateHttpsListener
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - RedirectConfig:
            Protocol: HTTPS
            StatusCode: HTTP_301
            Port: 443
          Type: redirect
      LoadBalancerArn: !If [ CreateLoadBalancer, !Ref LoadBalancer, !Ref LoadBalancerArn ]
      Port: 80
      Protocol: HTTP
#      SslPolicy: !Ref SslPolicy

  LoadBalancerListenerRule:
    Condition: CreateLoadBalancerListenerRule
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
      Conditions:
        - RuleCondition
      ListenerArn: !Ref LoadBalancerListenerArn
      Priority: Integer

#4) Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckPort: !Ref Port
      HealthCheckProtocol: !Ref Protocol
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      Name: !Sub ${ApplicationName}-${Stage}-tg
      Port: !Ref Port
      Protocol: !Ref Protocol
      UnhealthyThresholdCount: 2
      VpcId: !Ref VpcId

#6) Security Groups: Ssh and Web
  SshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${ApplicationName}-${Stage}-ssh-security-group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !If [ HasPublicIpAddress, '0.0.0.0/0', !Ref VpcCidr ]
      VpcId: !Ref VpcId

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${ApplicationName}-${Stage}-web-security-group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref Port
          ToPort: !Ref Port
          CidrIp: !If [ HasPublicIpAddress, '0.0.0.0/0', !Ref VpcCidr ]
      VpcId: !Ref VpcId

#7) Instance Profile/Iam Role
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref IamRole

  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ApplicationName}-${AWS::Region}-${Stage}-associate-address-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:AssociateAddress
                Resource:
                  - '*'
        - PolicyName: !Sub ${ApplicationName}-${AWS::Region}-${Stage}-codedeploy-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                Resource:
                  - '*'

#9) CodeDeploy Group
  CodeDeployGroup:
    Condition: CreateCodeDeployGroup
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      AutoScalingGroups:
        - !Ref AutoScalingGroup
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      DeploymentGroupName: !Sub ${ApplicationName}-${Stage}-${Sequence}
      LoadBalancerInfo:
        TargetGroupInfoList:
          - Name: !GetAtt TargetGroup.TargetGroupName
      ServiceRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/CodeDeployServiceRole'

Outputs:

  Cidr:
    Value: !If [ HasPublicIpAddress, '0.0.0.0/0', !Ref VpcCidr ]

  HasPublicIpAddress:
    Value: !Ref AssociatePublicIpAddress
