AWSTemplateFormatVersion: 2010-09-09
Description: ---
#Metadata:

Parameters:

  BastionAmiId:
    Default: none
    Type: String

  BastionInstanceType:
    Default: t3.nano
    Type: String

  CidrClassB:
    Type: String

  Name:
    Type: String

  Region:
    Type: String

  StackUrl:
    Type: String

  Stage:
    Default: dev
    Type: String

#Mappings:

Conditions:

  HasBastion: !Not [ !Equals [ !Ref BastionAmiId, none ] ]

Resources:

  BastionStack:
    Type: AWS::CloudFormation::Stack
    Condition: HasBastion
    Properties:
      Parameters:
        AmiId: !Ref BastionAmiId
        InstanceType: !Ref BastionInstanceType
        Stage: !Ref Stage
        VpcId: !GetAtt VpcSubStack.Outputs.VpcId
      TemplateUrl: !Sub ${StackUrl]/bastion.yaml

  VpcSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CidrClassB: !Ref CidrClassB
        Name: !Ref Name
        Region: !Ref Region
        Stage: !Ref Stage
      TemplateURL: !Sub ${StackUrl}/vpc.yaml

#Outputs:
