AWSTemplateFormatVersion: 2010-09-09
Description: ---
#Metadata:

Parameters:

  CidrClassB:
    Type: String

  Name:
    Type: String

  Region:
    Type: String

  StackUrl:
    Type: String

  Stage:
    Default: dev
    Type: String

#Mappings:

#Conditions:

Resources:

  VpcSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CidrClassB: !Ref CidrClassB
        Name: !Ref Name
        Region: !Ref Region
        Stage: !Ref Stage
      TemplateURL: !Sub {StackUrl}/vpc.yaml

#Outputs:
